import React, { useState } from 'react';
import { ExtractionResult } from '../types';
import { Download, Copy, CheckCircle, FileText, Calendar, Hash, PenTool, Code2, Ruler, CircleDashed, MoveHorizontal, Printer } from 'lucide-react';
import { downloadCSV } from '../utils/fileUtils';
import { PythonExportModal } from './PythonExportModal';

interface BOMResultsProps {
  result: ExtractionResult;
}

export const BOMResults: React.FC<BOMResultsProps> = ({ result }) => {
  const [copied, setCopied] = useState(false);
  const [showPythonModal, setShowPythonModal] = useState(false);
  const { metadata, bom, dimensions } = result;

  const handleCopy = () => {
    // Format text for clipboard
    let text = `Drawing: ${metadata.title || 'N/A'}\n\n`;
    
    if (dimensions && dimensions.length > 0) {
      text += `DIMENSIONS\nFeature\tType\tValue\tUnit\tNotes\n`;
      text += dimensions.map(d => `${d.feature}\t${d.type}\t${d.value}\t${d.unit}\t${d.notes}`).join('\n');
      text += `\n\n`;
    }

    text += `BILL OF MATERIALS\nItem\tPart No\tDescription\tQty\tMaterial\tRemarks\n`;
    text += bom.map(item => 
      `${item.itemNumber}\t${item.partNumber}\t${item.description}\t${item.quantity}\t${item.material}\t${item.remarks}`
    ).join('\n');

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const getDimensionIcon = (type: string) => {
    const t = type.toLowerCase();
    if (t.includes('radius') || t.includes('diameter') || t.includes('circle') || t.includes('hole')) {
      return <CircleDashed className="w-4 h-4 text-indigo-500" />;
    }
    if (t.includes('length') || t.includes('width') || t.includes('height')) {
      return <MoveHorizontal className="w-4 h-4 text-teal-500" />;
    }
    return <Ruler className="w-4 h-4 text-slate-500" />;
  };

  if (!bom && !metadata && !dimensions) return null;

  return (
    <>
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
        
        {/* Print Only Header */}
        <div className="hidden print:block border-b-2 border-slate-900 pb-4 mb-6">
          <div className="flex justify-between items-end">
             <div>
               <h1 className="text-3xl font-bold text-slate-900">Engineering Drawing Analysis</h1>
               <p className="text-slate-500 mt-1">Generated by BOM Extractor AI</p>
             </div>
             <div className="text-right">
               <p className="text-sm text-slate-500">Date: {new Date().toLocaleDateString()}</p>
             </div>
          </div>
        </div>

        {/* Title Block Metadata Section */}
        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm break-inside-avoid">
          <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4 border-b border-slate-100 pb-2">
            Drawing Readings (Title Block)
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div className="flex items-start gap-3">
              <div className="p-2 bg-blue-50 text-blue-600 rounded-lg no-print">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs text-slate-500 font-medium">Title</p>
                <p className="text-sm font-semibold text-slate-900">{metadata.title || 'Not detected'}</p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="p-2 bg-purple-50 text-purple-600 rounded-lg no-print">
                <Hash className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs text-slate-500 font-medium">Drawing No. / Rev</p>
                <p className="text-sm font-semibold text-slate-900">
                  {metadata.drawingNumber || '-'} <span className="text-slate-400">/</span> {metadata.revision || '-'}
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="p-2 bg-orange-50 text-orange-600 rounded-lg no-print">
                <PenTool className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs text-slate-500 font-medium">Drawn By</p>
                <p className="text-sm font-semibold text-slate-900">{metadata.drawnBy || 'Not detected'}</p>
              </div>
            </div>

            <div className="flex items-start gap-3 lg:col-span-3">
              <div className="p-2 bg-green-50 text-green-600 rounded-lg no-print">
                <Calendar className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs text-slate-500 font-medium">Date</p>
                <p className="text-sm font-semibold text-slate-900">{metadata.date || 'Not detected'}</p>
              </div>
            </div>
          </div>
        </div>

        {/* Dimensions Section */}
        {dimensions && dimensions.length > 0 && (
          <div className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm break-inside-avoid">
            <div className="bg-slate-50 px-6 py-4 border-b border-slate-200">
               <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wide flex items-center gap-2">
                 <Ruler className="w-4 h-4 text-slate-500" />
                 Dimensions & Geometry
               </h3>
            </div>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-slate-100">
                <thead className="bg-white">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Feature</th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Type</th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Value</th>
                    <th className="px-6 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">Notes</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {dimensions.map((dim, idx) => (
                    <tr key={idx} className="hover:bg-slate-50">
                      <td className="px-6 py-3 text-sm font-medium text-slate-900">{dim.feature || '-'}</td>
                      <td className="px-6 py-3 text-sm text-slate-600 flex items-center gap-2">
                        <span className="no-print">{getDimensionIcon(dim.type)}</span>
                        {dim.type}
                      </td>
                      <td className="px-6 py-3 text-sm font-mono font-semibold text-slate-800">
                        {dim.value} <span className="text-slate-500 font-sans text-xs">{dim.unit}</span>
                      </td>
                      <td className="px-6 py-3 text-sm text-slate-500 italic">{dim.notes || '-'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* BOM Table Section */}
        <div className="space-y-4 break-inside-avoid">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 no-print">
            <h2 className="text-xl font-bold text-slate-900">Extracted Bill of Materials</h2>
            <div className="flex flex-wrap gap-2 w-full sm:w-auto">
              <button
                onClick={handlePrint}
                className="flex items-center justify-center gap-2 px-3 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors shadow-sm"
                title="Print Report"
              >
                <Printer className="w-4 h-4" />
                Print / PDF
              </button>
              <button
                onClick={() => setShowPythonModal(true)}
                className="flex items-center justify-center gap-2 px-3 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-yellow-50 hover:text-yellow-700 hover:border-yellow-200 transition-colors"
                title="View Python Script"
              >
                <Code2 className="w-4 h-4" />
                Python
              </button>
              <button
                onClick={handleCopy}
                className="flex items-center justify-center gap-2 px-3 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors"
              >
                {copied ? <CheckCircle className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied' : 'Copy'}
              </button>
              <button
                onClick={() => downloadCSV(bom, 'bom_readings.csv')}
                className="flex items-center justify-center gap-2 px-3 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors shadow-sm"
              >
                <Download className="w-4 h-4" />
                Export CSV
              </button>
            </div>
          </div>

          <h2 className="text-xl font-bold text-slate-900 hidden print:block mt-6 mb-2">Bill of Materials</h2>

          <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-slate-200">
                <thead className="bg-slate-50">
                  <tr>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Item No</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Part No</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Description</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Qty</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Material</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">Remarks</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-slate-200">
                  {bom.length > 0 ? (
                    bom.map((item, index) => (
                      <tr key={index} className="hover:bg-slate-50 transition-colors">
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900">{item.itemNumber || '-'}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-600 font-mono">{item.partNumber || '-'}</td>
                        <td className="px-6 py-4 text-sm text-slate-700">{item.description}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-900 font-semibold">{item.quantity}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-600">{item.material || '-'}</td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500 italic">{item.remarks || '-'}</td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={6} className="px-6 py-8 text-center text-slate-500 text-sm">
                        No BOM items found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
          <div className="text-center text-xs text-slate-400 mt-2 no-print">
            Verify all readings against the original drawing. AI extraction may vary based on image clarity.
          </div>
        </div>
      </div>

      <PythonExportModal isOpen={showPythonModal} onClose={() => setShowPythonModal(false)} />
    </>
  );
};